apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
    kind: pack
  name: demo-pack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      kind: pack
  template:
    metadata:
      labels:
        app: demo
        kind: pack
    spec:
      containers:
      - image: placeholder:placeholder
        name: demo
        
        ports:
        - containerPort: 8000