apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../_base

resources:
- deployment.yaml

images:
- name: placeholder
  newName: harbor.sea.vmwhere.org/sea1/demo
  newTag: pack

replicas:
- name: demo-pack
  count: 1

patches:
  - path: ingress-patch.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: demo-ingress