apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: 
  virtualhost:
    fqdn: 
  routes:
  - conditions: 
    - prefix: /
    services:
    - name: demo2
      port: 5000
      #weight: 1000

       
      
  
  # includes:
  # - name: v3
  #   namespace: bni-v1
  #   conditions:
  #   - prefix: /hello